#ifndef GUARD_CONSTANTS_POKEDEX_H
#define GUARD_CONSTANTS_POKEDEX_H

// National Pokédex order
// These constants are NOT disabled by P_GEN_X_POKEMON to keep pokedex_orders.h clean.
enum NationalDexOrder
{
    NATIONAL_DEX_NONE,
    // Kanto
    NATIONAL_DEX_BULBASAUR,
    NATIONAL_DEX_IVYSAUR,
    NATIONAL_DEX_VENUSAUR,
    NATIONAL_DEX_TORCHIC,
    NATIONAL_DEX_COMBUSKEN,
    NATIONAL_DEX_BLAZIKEN,
    NATIONAL_DEX_TOTODILE,
    NATIONAL_DEX_CROCONAW,
    NATIONAL_DEX_FERALIGATR,
    NATIONAL_DEX_ROWLET,
    NATIONAL_DEX_DARTRIX,
    NATIONAL_DEX_DECIDUEYE,
    NATIONAL_DEX_CHIMCHAR,
    NATIONAL_DEX_MONFERNO,
    NATIONAL_DEX_INFERNAPE,
    NATIONAL_DEX_OSHAWOTT,
    NATIONAL_DEX_DEWOTT,
    NATIONAL_DEX_SAMUROTT,
    NATIONAL_DEX_SPRIGATITO,
    NATIONAL_DEX_FLORAGATO,
    NATIONAL_DEX_MEOWSCARADA,
    NATIONAL_DEX_SCORBUNNY,
    NATIONAL_DEX_RABOOT,
    NATIONAL_DEX_CINDERACE,
    NATIONAL_DEX_FROAKIE,
    NATIONAL_DEX_FROGADIER,
    NATIONAL_DEX_GRENINJA,
    NATIONAL_DEX_SENTRET,
    NATIONAL_DEX_FURRET,
    NATIONAL_DEX_PURRLOIN,
    NATIONAL_DEX_LIEPARD,
    NATIONAL_DEX_STARLY,
    NATIONAL_DEX_STARAVIA,
    NATIONAL_DEX_STARAPTOR,
    NATIONAL_DEX_WEEDLE,
    NATIONAL_DEX_KAKUNA,
    NATIONAL_DEX_BEEDRILL,
    NATIONAL_DEX_ROOKIDEE,
    NATIONAL_DEX_GRUBBIN,
    NATIONAL_DEX_CHARJABUG,
    NATIONAL_DEX_VIKAVOLT,
    NATIONAL_DEX_CORVISQUIRE,
    NATIONAL_DEX_CORVIKNIGHT,
    NATIONAL_DEX_YUNGOOS,
    NATIONAL_DEX_GUMSHOOS,
    NATIONAL_DEX_FIDOUGH,
    NATIONAL_DEX_DACHSBUN,
    NATIONAL_DEX_SHINX,
    NATIONAL_DEX_LUXIO,
    NATIONAL_DEX_LUXRAY,
    NATIONAL_DEX_FLETCHLING,
    NATIONAL_DEX_FLETCHINDER,
    NATIONAL_DEX_TALONFLAME,
    NATIONAL_DEX_SPEAROW,
    NATIONAL_DEX_FEAROW,
    NATIONAL_DEX_PATRAT,
    NATIONAL_DEX_WATCHOG,
    NATIONAL_DEX_NICKIT,
    NATIONAL_DEX_THIEVUL,
    NATIONAL_DEX_LEDYBA,
    NATIONAL_DEX_LEDIAN,
    NATIONAL_DEX_EKANS,
    NATIONAL_DEX_ARBOK,
    NATIONAL_DEX_LOTAD,
    NATIONAL_DEX_LOMBRE,
    NATIONAL_DEX_LUDICOLO,
    NATIONAL_DEX_SEEDOT,
    NATIONAL_DEX_NUZLEAF,
    NATIONAL_DEX_SHIFTRY,
    NATIONAL_DEX_TAROUNTULA,
    NATIONAL_DEX_SPIDOPS,
    NATIONAL_DEX_VENONAT,
    NATIONAL_DEX_VENOMOTH,
    NATIONAL_DEX_SHROOMISH,
    NATIONAL_DEX_BRELOOM,
    NATIONAL_DEX_KRICKETOT,
    NATIONAL_DEX_KRICKETUNE,
    NATIONAL_DEX_VENIPEDE,
    NATIONAL_DEX_WHIRLIPEDE,
    NATIONAL_DEX_SCOLIPEDE,
    NATIONAL_DEX_ROGGENROLA,
    NATIONAL_DEX_BOLDORE,
    NATIONAL_DEX_GIGALITH,
    NATIONAL_DEX_ROLYCOLY,
    NATIONAL_DEX_CARKOL,
    NATIONAL_DEX_COALOSSAL,
    NATIONAL_DEX_SLUGMA,
    NATIONAL_DEX_MAGCARGO,
    NATIONAL_DEX_ZUBAT,
    NATIONAL_DEX_GOLBAT,
    NATIONAL_DEX_CROBAT,
    NATIONAL_DEX_CLEFFA,
    NATIONAL_DEX_CLEFAIRY,
    NATIONAL_DEX_CLEFABLE,
    NATIONAL_DEX_SPINARAK,
    NATIONAL_DEX_ARIADOS,
    NATIONAL_DEX_PARAS,
    NATIONAL_DEX_PARASECT,
    NATIONAL_DEX_MORELULL,
    NATIONAL_DEX_SHIINOTIC,
    NATIONAL_DEX_FOMANTIS,
    NATIONAL_DEX_LURANTIS,
    NATIONAL_DEX_BONSLY,
    NATIONAL_DEX_SUDOWOODO,
    NATIONAL_DEX_COTTONEE,
    NATIONAL_DEX_WHIMSICOTT,
    NATIONAL_DEX_PETILIL,
    NATIONAL_DEX_LILLIGANT,
    NATIONAL_DEX_CUTIEFLY,
    NATIONAL_DEX_RIBOMBEE,
    NATIONAL_DEX_FLABEBE,
    NATIONAL_DEX_FLOETTE,
    NATIONAL_DEX_FLORGES,
    NATIONAL_DEX_SUNKERN,
    NATIONAL_DEX_SUNFLORA,
    NATIONAL_DEX_SURSKIT,
    NATIONAL_DEX_MASQUERAIN,
    NATIONAL_DEX_COMBEE,
    NATIONAL_DEX_VESPIQUEN,
    NATIONAL_DEX_DEWPIDER,
    NATIONAL_DEX_ARAQUANID,
    NATIONAL_DEX_SIZZLIPEDE,
    NATIONAL_DEX_CENTISKORCH,
    NATIONAL_DEX_HOUNDOUR,
    NATIONAL_DEX_HOUNDOOM,
    NATIONAL_DEX_IGGLYBUFF,
    NATIONAL_DEX_JIGGLYPUFF,
    NATIONAL_DEX_WIGGLYTUFF,
    NATIONAL_DEX_MUNNA,
    NATIONAL_DEX_MUSHARNA,
    NATIONAL_DEX_VULPIX,
    NATIONAL_DEX_NINETALES,
    NATIONAL_DEX_PANCHAM,
    NATIONAL_DEX_PANGORO,
    NATIONAL_DEX_MASCHIFF,
    NATIONAL_DEX_MABOSSTIFF,
    NATIONAL_DEX_GROWLITHE,
    NATIONAL_DEX_ARCANINE,
    NATIONAL_DEX_AZURILL,
    NATIONAL_DEX_MARILL,
    NATIONAL_DEX_AZUMARILL,
    NATIONAL_DEX_PLUSLE,
    NATIONAL_DEX_MINUN,
    NATIONAL_DEX_PACHIRISU,
    NATIONAL_DEX_PAWMI,
    NATIONAL_DEX_PAWMO,
    NATIONAL_DEX_PAWMOT,
    NATIONAL_DEX_ABRA,
    NATIONAL_DEX_KADABRA,
    NATIONAL_DEX_ALAKAZAM,
    NATIONAL_DEX_MACHOP,
    NATIONAL_DEX_MACHOKE,
    NATIONAL_DEX_MACHAMP,
    NATIONAL_DEX_PONYTA,
    NATIONAL_DEX_RAPIDASH,
    NATIONAL_DEX_PHANPY,
    NATIONAL_DEX_DONPHAN,
    NATIONAL_DEX_DODUO,
    NATIONAL_DEX_DODRIO,
    NATIONAL_DEX_HELIOPTILE,
    NATIONAL_DEX_HELIOLISK,
    NATIONAL_DEX_TOXEL,
    NATIONAL_DEX_TOXTRICITY,
    NATIONAL_DEX_GOLDEEN,
    NATIONAL_DEX_SEAKING,
    NATIONAL_DEX_PSYDUCK,
    NATIONAL_DEX_GOLDUCK,
    NATIONAL_DEX_CHINCHOU,
    NATIONAL_DEX_LANTURN,
    NATIONAL_DEX_STARYU,
    NATIONAL_DEX_STARMIE,
    NATIONAL_DEX_SLOWPOKE,
    NATIONAL_DEX_SLOWBRO,
    NATIONAL_DEX_SLOWKING,
    NATIONAL_DEX_CLOBBOPUS,
    NATIONAL_DEX_GRAPPLOCT,
    NATIONAL_DEX_SANDYGAST,
    NATIONAL_DEX_PALOSSAND,
    NATIONAL_DEX_GULPIN,
    NATIONAL_DEX_SWALOT,
    NATIONAL_DEX_SKITTY,
    NATIONAL_DEX_DELCATTY,
    NATIONAL_DEX_SNUBBULL,
    NATIONAL_DEX_GRANBULL,
    NATIONAL_DEX_BUNEARY,
    NATIONAL_DEX_LOPUNNY,
    NATIONAL_DEX_GLAMEOW,
    NATIONAL_DEX_PURUGLY,
    NATIONAL_DEX_VAROOM,
    NATIONAL_DEX_REVAVROOM,
    NATIONAL_DEX_TRUBBISH,
    NATIONAL_DEX_GARBODOR,
    NATIONAL_DEX_SHROODLE,
    NATIONAL_DEX_GRAFAIAI,
    NATIONAL_DEX_DRIFLOON,
    NATIONAL_DEX_DRIFBLIM,
    NATIONAL_DEX_FRILLISH,
    NATIONAL_DEX_JELLICENT,
    NATIONAL_DEX_GREAVARD,
    NATIONAL_DEX_HOUNDSTONE,
    NATIONAL_DEX_SINISTEA,
    NATIONAL_DEX_POLTEAGEIST,
    NATIONAL_DEX_GASTLY,
    NATIONAL_DEX_HAUNTER,
    NATIONAL_DEX_GENGAR,
    NATIONAL_DEX_LITWICK,
    NATIONAL_DEX_LAMPENT,
    NATIONAL_DEX_CHANDELURE,
    NATIONAL_DEX_DROWZEE,
    NATIONAL_DEX_HYPNO,
    NATIONAL_DEX_WYNAUT,
    NATIONAL_DEX_WOBBUFFET,
    NATIONAL_DEX_BRONZOR,
    NATIONAL_DEX_BRONZONG,
    NATIONAL_DEX_CHINGLING,
    NATIONAL_DEX_CHIMECHO,
    NATIONAL_DEX_LUNATONE,
    NATIONAL_DEX_SOLROCK,
    NATIONAL_DEX_DARUMAKA,
    NATIONAL_DEX_DARMANITAN,
    NATIONAL_DEX_ELGYEM,
    NATIONAL_DEX_BEHEEYEM,
    NATIONAL_DEX_BALTOY,
    NATIONAL_DEX_CLAYDOL,
    NATIONAL_DEX_NATU,
    NATIONAL_DEX_XATU,
    NATIONAL_DEX_FLITTLE,
    NATIONAL_DEX_ESPATHRA,
    NATIONAL_DEX_SIGILYPH,
    NATIONAL_DEX_DWEBBLE,
    NATIONAL_DEX_CRUSTLE,
    NATIONAL_DEX_NACLI,
    NATIONAL_DEX_NACLSTACK,
    NATIONAL_DEX_GARGANACL,
    NATIONAL_DEX_MARACTUS,
    NATIONAL_DEX_STONJOURNER,
    NATIONAL_DEX_CUBONE,
    NATIONAL_DEX_MAROWAK,
    NATIONAL_DEX_RELLOR,
    NATIONAL_DEX_RABSCA,
    NATIONAL_DEX_SKORUPI,
    NATIONAL_DEX_DRAPION,
    NATIONAL_DEX_CAPSAKID,
    NATIONAL_DEX_SCOVILLAIN,
    NATIONAL_DEX_CACNEA,
    NATIONAL_DEX_CACTURNE,
    NATIONAL_DEX_BRAMBLIN,
    NATIONAL_DEX_BRAMBLEGHAST,
    NATIONAL_DEX_RIOLU,
    NATIONAL_DEX_LUCARIO,
    NATIONAL_DEX_TINKATINK,
    NATIONAL_DEX_TINKATUFF,
    NATIONAL_DEX_TINKATON,
    NATIONAL_DEX_TYMPOLE,
    NATIONAL_DEX_PALPITOAD,
    NATIONAL_DEX_SEISMITOAD,
    NATIONAL_DEX_CLAUNCHER,
    NATIONAL_DEX_CLAWITZER,
    NATIONAL_DEX_SANDILE,
    NATIONAL_DEX_KROKOROK,
    NATIONAL_DEX_KROOKODILE,
    NATIONAL_DEX_CLAMPERL,
    NATIONAL_DEX_HUNTAIL,
    NATIONAL_DEX_GOREBYSS,
    NATIONAL_DEX_REMORAID,
    NATIONAL_DEX_OCTILLERY,
    NATIONAL_DEX_FINNEON,
    NATIONAL_DEX_LUMINEON,
    NATIONAL_DEX_MAGIKARP,
    NATIONAL_DEX_GYARADOS,
    NATIONAL_DEX_WAILMER,
    NATIONAL_DEX_WAILORD,
    NATIONAL_DEX_BERGMITE,
    NATIONAL_DEX_AVALUGG,
    NATIONAL_DEX_CRABRAWLER,
    NATIONAL_DEX_CRABOMINABLE,
    NATIONAL_DEX_VANILLITE,
    NATIONAL_DEX_VANILLISH,
    NATIONAL_DEX_VANILLUXE,
    NATIONAL_DEX_SNOM,
    NATIONAL_DEX_FROSMOTH,
    NATIONAL_DEX_KABUTO,
    NATIONAL_DEX_KABUTOPS,
    NATIONAL_DEX_ANORITH,
    NATIONAL_DEX_ARMALDO,
    NATIONAL_DEX_CRANIDOS,
    NATIONAL_DEX_RAMPARDOS,
    NATIONAL_DEX_ARCHEN,
    NATIONAL_DEX_ARCHEOPS,
    NATIONAL_DEX_TYRUNT,
    NATIONAL_DEX_TYRANTRUM,
    NATIONAL_DEX_KANGASKHAN,
    NATIONAL_DEX_MILTANK,
    NATIONAL_DEX_LAPRAS,
    NATIONAL_DEX_PINSIR,
    NATIONAL_DEX_HERACROSS,
    NATIONAL_DEX_TROPIUS,
    NATIONAL_DEX_COMFEY,
    NATIONAL_DEX_SPINDA,
    NATIONAL_DEX_CASTFORM,
    NATIONAL_DEX_ABSOL,
    NATIONAL_DEX_SPIRITOMB,
    NATIONAL_DEX_CARNIVINE,
    NATIONAL_DEX_KLEFKI,
    NATIONAL_DEX_CRYOGONAL,
    NATIONAL_DEX_DRUDDIGON,
    NATIONAL_DEX_PYUKUMUKU,
    NATIONAL_DEX_MIMIKYU,
    NATIONAL_DEX_BRUXISH,
    NATIONAL_DEX_DHELMISE,
    NATIONAL_DEX_FALINKS,
    NATIONAL_DEX_CYCLIZAR,
    NATIONAL_DEX_WISHIWASHI,
    NATIONAL_DEX_MUNCHLAX,
    NATIONAL_DEX_SNORLAX,
    NATIONAL_DEX_NOSEPASS,
    NATIONAL_DEX_PROBOPASS,
    NATIONAL_DEX_TANGELA,
    NATIONAL_DEX_TANGROWTH,
    NATIONAL_DEX_SWINUB,
    NATIONAL_DEX_PILOSWINE,
    NATIONAL_DEX_MAMOSWINE,
    NATIONAL_DEX_BUDEW,
    NATIONAL_DEX_ROSELIA,
    NATIONAL_DEX_ROSERADE,
    NATIONAL_DEX_MAGNEMITE,
    NATIONAL_DEX_MAGNETON,
    NATIONAL_DEX_MAGNEZONE,
    NATIONAL_DEX_GLIGAR,
    NATIONAL_DEX_GLISCOR,
    NATIONAL_DEX_PORYGON,
    NATIONAL_DEX_PORYGON2,
    NATIONAL_DEX_PORYGON_Z,
    NATIONAL_DEX_MISDREAVUS,
    NATIONAL_DEX_MISMAGIUS,
    NATIONAL_DEX_TOGEPI,
    NATIONAL_DEX_TOGETIC,
    NATIONAL_DEX_TOGEKISS,
    NATIONAL_DEX_SCYTHER,
    NATIONAL_DEX_SCIZOR,
    NATIONAL_DEX_KLEAVOR,
    NATIONAL_DEX_BASCULIN,
    NATIONAL_DEX_BASCULEGION,
    NATIONAL_DEX_TEDDIURSA,
    NATIONAL_DEX_URSARING,
    NATIONAL_DEX_URSALUNA,
    NATIONAL_DEX_KLINK,
    NATIONAL_DEX_KLANG,
    NATIONAL_DEX_KLINKLANG,
    NATIONAL_DEX_GOTHITA,
    NATIONAL_DEX_GOTHORITA,
    NATIONAL_DEX_GOTHITELLE,
    NATIONAL_DEX_SOLOSIS,
    NATIONAL_DEX_DUOSION,
    NATIONAL_DEX_REUNICLUS,
    NATIONAL_DEX_INKAY,
    NATIONAL_DEX_MALAMAR,
    NATIONAL_DEX_RALTS,
    NATIONAL_DEX_KIRLIA,
    NATIONAL_DEX_GARDEVOIR,
    NATIONAL_DEX_GALLADE,
    NATIONAL_DEX_HATENNA,
    NATIONAL_DEX_HATTREM,
    NATIONAL_DEX_HATTERENE,
    NATIONAL_DEX_IMPIDIMP,
    NATIONAL_DEX_MORGREM,
    NATIONAL_DEX_GRIMMSNARL,
    NATIONAL_DEX_FEEBAS,
    NATIONAL_DEX_MILOTIC,
    NATIONAL_DEX_SKRELP,
    NATIONAL_DEX_DRAGALGE,
    NATIONAL_DEX_LARVESTA,
    NATIONAL_DEX_VOLCARONA,
    NATIONAL_DEX_TRAPINCH,
    NATIONAL_DEX_VIBRAVA,
    NATIONAL_DEX_FLYGON,
    NATIONAL_DEX_DURALUDON,
    NATIONAL_DEX_ARCHALUDON,
    NATIONAL_DEX_GLIMMET,
    NATIONAL_DEX_GLIMMORA,
    NATIONAL_DEX_AXEW,
    NATIONAL_DEX_FRAXURE,
    NATIONAL_DEX_HAXORUS,
    NATIONAL_DEX_GIMMIGHOUL,
    NATIONAL_DEX_GHOLDENGO,
    NATIONAL_DEX_GOLETT,
    NATIONAL_DEX_GOLURK,
    NATIONAL_DEX_BAGON,
    NATIONAL_DEX_SHELGON,
    NATIONAL_DEX_SALAMENCE,
    NATIONAL_DEX_DREEPY,
    NATIONAL_DEX_DRAKLOAK,
    NATIONAL_DEX_DRAGAPULT,
    NATIONAL_DEX_BELDUM,
    NATIONAL_DEX_METANG,
    NATIONAL_DEX_METAGROSS,
    NATIONAL_DEX_DRATINI,
    NATIONAL_DEX_DRAGONAIR,
    NATIONAL_DEX_DRAGONITE,
    NATIONAL_DEX_LARVITAR,
    NATIONAL_DEX_PUPITAR,
    NATIONAL_DEX_TYRANITAR,
    NATIONAL_DEX_DEINO,
    NATIONAL_DEX_ZWEILOUS,
    NATIONAL_DEX_HYDREIGON,
    NATIONAL_DEX_NIHILEGO,
    NATIONAL_DEX_BUZZWOLE,
    NATIONAL_DEX_PHEROMOSA,
    NATIONAL_DEX_XURKITREE,
    NATIONAL_DEX_CELESTEELA,
    NATIONAL_DEX_KARTANA,
    NATIONAL_DEX_GUZZLORD,
    NATIONAL_DEX_POIPOLE,
    NATIONAL_DEX_NAGANADEL,
    NATIONAL_DEX_STAKATAKA,
    NATIONAL_DEX_BLACEPHALON,
    NATIONAL_DEX_REGIROCK,
    NATIONAL_DEX_REGICE,
    NATIONAL_DEX_REGISTEEL,
    NATIONAL_DEX_REGIELEKI,
    NATIONAL_DEX_REGIDRAGO,
    NATIONAL_DEX_WO_CHIEN,
    NATIONAL_DEX_CHIEN_PAO,
    NATIONAL_DEX_TING_LU,
    NATIONAL_DEX_CHI_YU,
    NATIONAL_DEX_TAPU_KOKO,
    NATIONAL_DEX_TAPU_LELE,
    NATIONAL_DEX_TAPU_BULU,
    NATIONAL_DEX_TAPU_FINI,
    NATIONAL_DEX_LUGIA,
    NATIONAL_DEX_HO_OH,
    NATIONAL_DEX_RAYQUAZA,
    NATIONAL_DEX_REGIGIGAS,
    NATIONAL_DEX_GIRATINA,
    NATIONAL_DEX_CRESSELIA,
    NATIONAL_DEX_DARKRAI,
    NATIONAL_DEX_RESHIRAM,
    NATIONAL_DEX_ZEKROM,
    NATIONAL_DEX_KYUREM,
    NATIONAL_DEX_XERNEAS,
    NATIONAL_DEX_YVELTAL,
    NATIONAL_DEX_ZACIAN,
    NATIONAL_DEX_ZAMAZENTA,
    NATIONAL_DEX_ETERNATUS,
    NATIONAL_DEX_KORAIDON,
    NATIONAL_DEX_MIRAIDON,
    NATIONAL_DEX_VICTINI,
    NATIONAL_DEX_MEW,
    NATIONAL_DEX_CELEBI,
    NATIONAL_DEX_JIRACHI,
    NATIONAL_DEX_MELOETTA,
    NATIONAL_DEX_GENESECT,
    NATIONAL_DEX_VOLCANION,
    NATIONAL_DEX_MAGEARNA,
    NATIONAL_DEX_ZERAORA,
    // Johto
    // Sinnoh
    // Unova
    // Kalos

    // Alola
    // Galar
};

#define JOHTO_DEX_COUNT     NATIONAL_DEX_CELEBI

#if P_GEN_9_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ZERAORA
#elif P_GEN_9_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_HYDRAPPLE
#elif P_PALDEAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_CLODSIRE

#elif P_GEN_8_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ENAMORUS
#elif P_HISUIAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_OVERQWIL
#elif P_GEN_8_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_URSALUNA
#elif P_GALARIAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_RUNERIGUS

#elif P_GEN_7_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_MELMETAL

#elif P_GEN_6_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_VOLCANION
#elif P_GEN_6_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_SYLVEON

#elif P_GEN_5_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_GENESECT

#elif P_GEN_4_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ARCEUS
#elif P_GEN_4_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_FROSLASS

#else
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_DEOXYS
#endif

#define POKEMON_SLOTS_NUMBER (NATIONAL_DEX_COUNT + 1)

#if P_NEW_EVOS_IN_REGIONAL_DEX
#define HOENN_DEX_IF(config, ...) CAT(HOENN_DEX_IF_, config)(__VA_ARGS__)
#define HOENN_DEX_IF_0(...)
#define HOENN_DEX_IF_1(...) __VA_ARGS__
#else
#define HOENN_DEX_IF(config, ...)
#endif

#define FOREACH_SPECIES_IN_HOENN_DEX_ORDER(F) \
    F(TORCHIC) \
    F(COMBUSKEN) \
    F(BLAZIKEN) \
    F(LOTAD) \
    F(LOMBRE) \
    F(LUDICOLO) \
    F(SEEDOT) \
    F(NUZLEAF) \
    F(SHIFTRY) \
    F(RALTS) \
    F(KIRLIA) \
    F(GARDEVOIR) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(GALLADE)) \
    F(SURSKIT) \
    F(MASQUERAIN) \
    F(SHROOMISH) \
    F(BRELOOM) \
    F(ABRA) \
    F(KADABRA) \
    F(ALAKAZAM) \
    F(GOLDEEN) \
    F(SEAKING) \
    F(MAGIKARP) \
    F(GYARADOS) \
    F(AZURILL) \
    F(MARILL) \
    F(AZUMARILL) \
    F(NOSEPASS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(PROBOPASS)) \
    F(SKITTY) \
    F(DELCATTY) \
    F(ZUBAT) \
    F(GOLBAT) \
    F(CROBAT) \
    F(MACHOP) \
    F(MACHOKE) \
    F(MACHAMP) \
    F(PLUSLE) \
    F(MINUN) \
    F(MAGNEMITE) \
    F(MAGNETON) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGNEZONE)) \
    F(DODUO) \
    F(DODRIO) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(BUDEW)) \
    F(ROSELIA) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(ROSERADE)) \
    F(GULPIN) \
    F(SWALOT) \
    F(WAILMER) \
    F(WAILORD) \
    F(SLUGMA) \
    F(MAGCARGO) \
    F(SPINDA) \
    F(TRAPINCH) \
    F(VIBRAVA) \
    F(FLYGON) \
    F(CACNEA) \
    F(CACTURNE) \
    F(LUNATONE) \
    F(SOLROCK) \
    F(BALTOY) \
    F(CLAYDOL) \
    F(ANORITH) \
    F(ARMALDO) \
    F(IGGLYBUFF) \
    F(JIGGLYPUFF) \
    F(WIGGLYTUFF) \
    F(FEEBAS) \
    F(MILOTIC) \
    F(CASTFORM) \
    F(STARYU) \
    F(STARMIE) \
    F(TROPIUS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(CHINGLING)) \
    F(CHIMECHO) \
    F(ABSOL) \
    F(VULPIX) \
    F(NINETALES) \
    F(PSYDUCK) \
    F(GOLDUCK) \
    F(WYNAUT) \
    F(WOBBUFFET) \
    F(NATU) \
    F(XATU) \
    F(PHANPY) \
    F(DONPHAN) \
    F(PINSIR) \
    F(HERACROSS) \
    F(CLAMPERL) \
    F(HUNTAIL) \
    F(GOREBYSS) \
    F(CHINCHOU) \
    F(LANTURN) \
    F(BAGON) \
    F(SHELGON) \
    F(SALAMENCE) \
    F(BELDUM) \
    F(METANG) \
    F(METAGROSS) \
    F(REGIROCK) \
    F(REGICE) \
    F(REGISTEEL) \
    F(RAYQUAZA) \
    F(JIRACHI)

// Hoenn Pokédex order
enum HoennDexOrder
{
    HOENN_DEX_NONE,
    #define HOENN_DEX_ENUM(name) HOENN_DEX_ ##name,
    FOREACH_SPECIES_IN_HOENN_DEX_ORDER(HOENN_DEX_ENUM)
    #undef HOENN_DEX_ENUM
};



#if P_NEW_EVOS_IN_REGIONAL_DEX
#define KANTO_DEX_IF(config, ...) CAT(KANTO_DEX_IF_, config)(__VA_ARGS__)
#define KANTO_DEX_IF_0(...)
#define KANTO_DEX_IF_1(...) __VA_ARGS__
#else
#define KANTO_DEX_IF(config, ...)
#endif

#define FOREACH_SPECIES_IN_KANTO_DEX_ORDER(F) \
    F(BULBASAUR) \
    F(IVYSAUR) \
    F(VENUSAUR) \
    F(WEEDLE) \
    F(KAKUNA) \
    F(BEEDRILL) \
    F(SPEAROW) \
    F(FEAROW) \
    F(EKANS) \
    F(ARBOK) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(CLEFFA)) \
    F(CLEFAIRY) \
    F(CLEFABLE) \
    F(VULPIX) \
    F(NINETALES) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(IGGLYBUFF)) \
    F(JIGGLYPUFF) \
    F(WIGGLYTUFF) \
    F(ZUBAT) \
    F(GOLBAT) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(CROBAT)) \
    F(PARAS) \
    F(PARASECT) \
    F(VENONAT) \
    F(VENOMOTH) \
    F(PSYDUCK) \
    F(GOLDUCK) \
    F(GROWLITHE) \
    F(ARCANINE) \
    F(ABRA) \
    F(KADABRA) \
    F(ALAKAZAM) \
    F(MACHOP) \
    F(MACHOKE) \
    F(MACHAMP) \
    F(PONYTA) \
    F(RAPIDASH) \
    F(SLOWPOKE) \
    F(SLOWBRO) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SLOWKING)) \
    F(MAGNEMITE) \
    F(MAGNETON) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGNEZONE)) \
    F(DODUO) \
    F(DODRIO) \
    F(GASTLY) \
    F(HAUNTER) \
    F(GENGAR) \
    F(DROWZEE) \
    F(HYPNO) \
    F(CUBONE) \
    F(MAROWAK) \
    F(TANGELA) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(TANGROWTH)) \
    F(KANGASKHAN) \
    F(GOLDEEN) \
    F(SEAKING) \
    F(STARYU) \
    F(STARMIE) \
    F(SCYTHER) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SCIZOR)) \
    KANTO_DEX_IF(P_GEN_8_CROSS_EVOS, F(KLEAVOR)) \
    F(PINSIR) \
    F(MAGIKARP) \
    F(GYARADOS) \
    F(LAPRAS) \
    F(PORYGON) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(PORYGON2)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(PORYGON_Z)) \
    F(KABUTO) \
    F(KABUTOPS) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MUNCHLAX)) \
    F(SNORLAX) \
    F(DRATINI) \
    F(DRAGONAIR) \
    F(DRAGONITE) \
    F(MEW)

// Kanto Pokedex order
enum KantoDexOrder
{
    KANTO_DEX_NONE,
    #define KANTO_DEX_ENUM(name) KANTO_DEX_ ##name,
    FOREACH_SPECIES_IN_KANTO_DEX_ORDER(KANTO_DEX_ENUM)
    #undef KANTO_DEX_ENUM
};

#define KANTO_DEX_COUNT (KANTO_DEX_MEW + 1)
#define HOENN_DEX_COUNT (HOENN_DEX_JIRACHI + 1)

#define REGIONAL_DEX_COUNT (IS_FRLG ? KANTO_DEX_COUNT : HOENN_DEX_COUNT)

#define DECAGRAMS_IN_POUND             453592
#define CM_PER_INCH                    2.54
#define CM_PER_INCH_FACTOR             (CM_PER_INCH * 100)
#define INCHES_IN_FOOT                 12
#define INCHES_IN_ONE_AND_HALF_FOOT    (INCHES_IN_FOOT * 1.5)
#define INCHES_IN_FOOT_FACTOR          (INCHES_IN_FOOT * 10)

#define WEIGHT_HEIGHT_STR_LEN          16
#define WEIGHT_HEIGHT_STR_MEM          (WEIGHT_HEIGHT_STR_LEN * sizeof(u8))

#define DEX_HEADER_X                   96
#define DEX_Y_TOP                      57
#define DEX_Y_BOTTOM                   73
#define DEX_MEASUREMENT_X              129

#define DEX_HGSS_HEADER_X_PADDING      59
#define DEX_HGSS_Y_TOP_PADDING         7
#define DEX_HGSS_Y_BOTTOM_PADDING      4
#define DEX_HGSS_MEASUREMENT_X_PADDING 51

enum
{
    DEX_MODE_HOENN,
    DEX_MODE_NATIONAL
};

enum
{
    FLAG_GET_SEEN,
    FLAG_GET_CAUGHT,
    FLAG_SET_SEEN,
    FLAG_SET_CAUGHT
};

#endif // GUARD_CONSTANTS_POKEDEX_H