#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT) \
    F(TAKE_DOWN) \
    F(CHARM) \
    F(ACID_SPRAY) \
    F(TRAILBLAZE) \
    F(MAGICAL_LEAF) \
    F(VENOSHOCK) \
    F(ENDURE) \
    F(FALSE_SWIPE) \
    F(BODY_SLAM) \
    F(SLEEP_TALK) \
    F(SEED_BOMB) \
    F(GRASS_KNOT) \
    F(SWORDS_DANCE) \
    F(SUBSTITUTE) \
    F(ENERGY_BALL) \
    F(HELPING_HAND) \
    F(GRASSY_TERRAIN) \
    F(GRASS_PLEDGE) \
    F(LEAF_STORM) \
    F(TERA_BLAST) \
    F(KNOCK_OFF) \
    F(WEATHER_BALL) \
    F(GRASSY_GLIDE) \
    F(DOUBLE_EDGE) \
    F(CURSE) \
    F(SCARY_FACE) \
    F(BULLDOZE) \
    F(POISON_JAB) \
    F(STOMPING_TANTRUM) \
    F(AMNESIA) \
    F(EARTH_POWER) \
    F(GIGA_IMPACT) \
    F(FRENZY_PLANT) \
    F(PETAL_BLIZZARD) \
    F(FIRE_FANG) \
    F(FIRE_SPIN) \
    F(METAL_CLAW) \
    F(SWIFT) \
    F(FLAME_CHARGE) \
    F(FLING) \
    F(DRAGON_TAIL) \
    F(SHADOW_CLAW) \
    F(FIRE_PUNCH) \
    F(THUNDER_PUNCH) \
    F(ROCK_SLIDE) \
    F(DRAGON_DANCE) \
    F(WILL_O_WISP) \
    F(CRUNCH) \
    F(DRAGON_PULSE) \
    F(HEAT_WAVE)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
