name: Discord Notifications

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_MSG=$(echo "${{ github.event.head_commit.message }}" | sed 's/"/\\"/g')
        
          curl -H "Content-Type: application/json" \
          -d "{
            \"username\": \"Meloetta\",
            \"embeds\": [
              {
                \"title\": \"🎶 Nouveau commit sur ${{ github.repository }}\",
                \"description\": \"**${{ github.sha }}**\n$COMMIT_MSG\n👤 ${{ github.actor }}\n🔗 https://github.com/${{ github.repository }}/commit/${{ github.sha }}\"
              }
            ]
          }" \
          "$DISCORD_WEBHOOK"