name: Discord Notifications

on:
  push:
  pull_request:
  release:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "username":"Meloetta",
            "avatar_url":"https://raw.githubusercontent.com/PMDCollab/SpriteCollab/master/portrait/0648/Normal.png",
            "content":"🎮 Nouvelle activité : ${{ github.event_name }} par ${{ github.actor }}"
          }' \
          "$DISCORD_WEBHOOK"